name: vulnerability scan workflow

on: push

jobs:
    meterian_scan:
        name: Meterian client scan
        runs-on: ubuntu-latest
        steps: 
          - name: Checkout
            uses: actions/checkout@v2
          - name: Scan project with the Meterian client
            uses: docker://meterian/cli:latest-node
            env:
                METERIAN_API_TOKEN: ${{ secrets.METERIAN_API_TOKEN }}
            with:
                args: #[ Meterian CLI Options ]
